### ISSUE TITLE
Kernel for rdf graphs

### ISSUE THREAD

**Issue by sbhttchryy** [ysig/GraKeL#33]
Hello, I have a Networkx multigraph that I have created using the [AIFB ](https://figshare.com/articles/AIFB_DataSet/745364)dataset. I want to use the kernels to perform classification tasks on nodes. Since these graphs have edge labels, do you have any suggestions as to what kernel might be good for this case?

**Comment by giannisnik** [comment]
Dear @sbhttchryy ,

All the kernels contained in GraKeL are kernels between graphs, i.e., each sample is a graph and not a node.

If in your problem, classes capture structural similarity (and not homophily), then you can use GraKeL if you follow this approach:

- create one graph for each node (e.g., its egonetwork of radius r) 
- then, formulate the problem as a graph classification one (instead of node classification)
