### ISSUE TITLE
Singular matrix for RandomWalk kernel

### ISSUE THREAD

**Issue by xia0pin9** [ysig/GraKeL#4]
I was testing some directed unlabeled unweighted graphs. One of them triggered the "Singular matrix" error, which corresponds to the following code:

```                
                def invert(n, w, v):
                    return (np.real(np.sum(v, axis=0))/n, np.real(w), np.real(np.sum(inv(v), axis=1))/n)

                def add_input(x):
                    return invert(x.shape[0], *eig(x))
```

**Comment by ysig** [comment]
As you can see [here](https://github.com/ysig/GraKeL/blob/develop/grakel/kernels/random_walk.py#L102) this line has been resolved [4 days before your post](https://github.com/ysig/GraKeL/blame/564db99978f44f9e4e199413a4a141644c156187/grakel/kernels/random_walk.py#L102) so it is normal that you have not seen it.

Please install the latest `grakel` from the repository.
Note: Random walk was designed for undirected graphs (i.e. directed with both directions of each edge - a symmetric adjacency matrix). Instead of doing `inv(v)` this was replaced with `v.T` as in the original paper, in order for the kernel to be faster in most cases and not to `crash`. The problem is that this equality (i.e. `inv(v) = v.T`) only holds if the adjacency matrix `A` is symmetric. In any other case it is an approximation.
